// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxKdqdm6xBsbNPipB1pwa8FCKgvbp5dAw',
    appId: '1:1092870181448:android:58db1b59b34ec7acb0be7d',
    messagingSenderId: '1092870181448',
    projectId: 'proyecto-esquel-gimnasio',
    databaseURL: 'https://proyecto-esquel-gimnasio-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-esquel-gimnasio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDafBPhcMeGX2FhU_2PVfVFSoCi4XZWZtE',
    appId: '1:1092870181448:ios:d0086790546436cdb0be7d',
    messagingSenderId: '1092870181448',
    projectId: 'proyecto-esquel-gimnasio',
    databaseURL: 'https://proyecto-esquel-gimnasio-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-esquel-gimnasio.appspot.com',
    androidClientId: '1092870181448-u2cv8uca9m7sjbtl3o9df2jqhhcv61tc.apps.googleusercontent.com',
    iosClientId: '1092870181448-chdps3n2kp4sgdkap57c891m9q51jku5.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoGimnacioEsquel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BkBn3S8ij4yJBv8LqzY74QyZhnMADhI',
    appId: '1:1092870181448:web:335a8b3b79ef1294b0be7d',
    messagingSenderId: '1092870181448',
    projectId: 'proyecto-esquel-gimnasio',
    authDomain: 'proyecto-esquel-gimnasio.firebaseapp.com',
    databaseURL: 'https://proyecto-esquel-gimnasio-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-esquel-gimnasio.appspot.com',
    measurementId: 'G-LE611X57SQ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_BkBn3S8ij4yJBv8LqzY74QyZhnMADhI',
    appId: '1:1092870181448:web:e3384c5ea93f862cb0be7d',
    messagingSenderId: '1092870181448',
    projectId: 'proyecto-esquel-gimnasio',
    authDomain: 'proyecto-esquel-gimnasio.firebaseapp.com',
    databaseURL: 'https://proyecto-esquel-gimnasio-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-esquel-gimnasio.appspot.com',
    measurementId: 'G-FKX3GC7YX0',
  );

}